ruby '2.0.0'
source 'https://rubygems.org'
gem 'sinatra'
gem 'bundler'
gem 'neo4j', '~>3.0'
gem 'nokogiri'
gem 'pry'
gem 'mechanize'
gem 'haml'
gem 'sass'
gem 'thin'
gem 'moped'
gem 'mongoid'
gem 'sinatra-websocket'
gem 'sinatra-contrib'
gem 'watir-webdriver'
gem 'watir-scroll'
gem 'bson_ext'
